version: "2"
services:
    app:
        build: ./ApacheDockerfile
        ports: 
            - "8001:80"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: vtiger
            MYSQL_USER: vtiger
            MYSQL_PASSWORD: vtiger
            MYSQL_ROOT_PASSWORD: vtiger
        volumes:
            - ./mysql:/var/lib/mysql
            - ./ApacheDockerfile/my.cnf:/etc/mysql/my.cnf
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: vtiger
            MYSQL_PASSWORD: vtiger
            MYSQL_ROOT_PASSWORD: vtiger
